-- Níveis de ensino
insert into public.education_levels (name, slug, order_index) values
  ('Educação Infantil', 'educacao-infantil', 0),
  ('Ensino Fundamental I', 'ensino-fundamental-i', 1),
  ('Ensino Fundamental II', 'ensino-fundamental-ii', 2),
  ('Ensino Médio', 'ensino-medio', 3);

-- Séries / anos (vinculados por slug do nível)
insert into public.grades (education_level_id, name, slug, order_index) values
  ((select id from public.education_levels where slug = 'educacao-infantil'), 'Bebês', 'bebes', 0),
  ((select id from public.education_levels where slug = 'educacao-infantil'), 'Crianças bem pequenas', 'criancas-bem-pequenas', 1),
  ((select id from public.education_levels where slug = 'educacao-infantil'), 'Crianças pequenas', 'criancas-pequenas', 2),
  ((select id from public.education_levels where slug = 'educacao-infantil'), 'Maternal', 'maternal', 3),
  ((select id from public.education_levels where slug = 'educacao-infantil'), 'Jardim I', 'jardim-i', 4),
  ((select id from public.education_levels where slug = 'educacao-infantil'), 'Jardim II', 'jardim-ii', 5),
  ((select id from public.education_levels where slug = 'educacao-infantil'), 'Pré-escola', 'pre-escola', 6),
  ((select id from public.education_levels where slug = 'ensino-fundamental-i'), '1º ano', '1-ano', 0),
  ((select id from public.education_levels where slug = 'ensino-fundamental-i'), '2º ano', '2-ano', 1),
  ((select id from public.education_levels where slug = 'ensino-fundamental-i'), '3º ano', '3-ano', 2),
  ((select id from public.education_levels where slug = 'ensino-fundamental-i'), '4º ano', '4-ano', 3),
  ((select id from public.education_levels where slug = 'ensino-fundamental-i'), '5º ano', '5-ano', 4),
  ((select id from public.education_levels where slug = 'ensino-fundamental-ii'), '6º ano', '6-ano', 0),
  ((select id from public.education_levels where slug = 'ensino-fundamental-ii'), '7º ano', '7-ano', 1),
  ((select id from public.education_levels where slug = 'ensino-fundamental-ii'), '8º ano', '8-ano', 2),
  ((select id from public.education_levels where slug = 'ensino-fundamental-ii'), '9º ano', '9-ano', 3),
  ((select id from public.education_levels where slug = 'ensino-medio'), '1ª série', '1-serie', 0),
  ((select id from public.education_levels where slug = 'ensino-medio'), '2ª série', '2-serie', 1),
  ((select id from public.education_levels where slug = 'ensino-medio'), '3ª série', '3-serie', 2);

-- Disciplinas (todas, dedupe entre níveis)
insert into public.subjects (name, slug, order_index) values
  ('Linguagem oral', 'linguagem-oral', 0),
  ('Coordenação motora', 'coordenacao-motora', 1),
  ('Musicalização', 'musicalizacao', 2),
  ('Artes visuais', 'artes-visuais', 3),
  ('Movimento', 'movimento', 4),
  ('Natureza e sociedade', 'natureza-e-sociedade', 5),
  ('Noções matemáticas', 'nocoes-matematicas', 6),
  ('Alfabetização inicial', 'alfabetizacao-inicial', 7),
  ('Contação de histórias', 'contacao-de-historias', 8),
  ('Psicomotricidade', 'psicomotricidade', 9),
  ('Educação socioemocional', 'educacao-socioemocional', 10),
  ('Brincadeiras e jogos', 'brincadeiras-e-jogos', 11),
  ('Datas comemorativas', 'datas-comemorativas', 12),
  ('Língua Portuguesa', 'lingua-portuguesa', 13),
  ('Matemática', 'matematica', 14),
  ('Ciências', 'ciencias', 15),
  ('História', 'historia', 16),
  ('Geografia', 'geografia', 17),
  ('Arte', 'arte', 18),
  ('Educação Física', 'educacao-fisica', 19),
  ('Língua Inglesa', 'lingua-inglesa', 20),
  ('Ensino Religioso', 'ensino-religioso', 21),
  ('Informática', 'informatica', 22),
  ('Educação Financeira', 'educacao-financeira', 23),
  ('Robótica', 'robotica', 24),
  ('Tecnologia e Computação', 'tecnologia-e-computacao', 25),
  ('Redação', 'redacao', 26),
  ('Literatura', 'literatura', 27),
  ('Língua Espanhola', 'lingua-espanhola', 28),
  ('Filosofia', 'filosofia', 29),
  ('Sociologia', 'sociologia', 30),
  ('Projeto de Vida', 'projeto-de-vida', 31),
  ('Geometria', 'geometria', 32),
  ('Estatística', 'estatistica', 33),
  ('Matemática Financeira', 'matematica-financeira', 34),
  ('Biologia', 'biologia', 35),
  ('Física', 'fisica', 36),
  ('Química', 'quimica', 37),
  ('Ciências da Natureza', 'ciencias-da-natureza', 38),
  ('Empreendedorismo', 'empreendedorismo', 39),
  ('Atualidades', 'atualidades', 40),
  ('Preparação para o ENEM', 'preparacao-para-o-enem', 41),
  ('Orientação profissional', 'orientacao-profissional', 42);

-- Tipos de material
insert into public.content_types (name, slug, order_index) values
  ('Atividade', 'atividade', 0),
  ('Lista de exercícios', 'lista-de-exercicios', 1),
  ('Avaliação', 'avaliacao', 2),
  ('Prova', 'prova', 3),
  ('Simulado', 'simulado', 4),
  ('Gabarito', 'gabarito', 5),
  ('Plano de aula', 'plano-de-aula', 6),
  ('Sequência didática', 'sequencia-didatica', 7),
  ('Projeto', 'projeto', 8),
  ('Roteiro de estudo', 'roteiro-de-estudo', 9),
  ('Resumo', 'resumo', 10),
  ('Mapa mental', 'mapa-mental', 11),
  ('Infográfico', 'infografico', 12),
  ('Apresentação', 'apresentacao', 13),
  ('Apostila', 'apostila', 14),
  ('Livro digital', 'livro-digital', 15),
  ('Texto de apoio', 'texto-de-apoio', 16),
  ('Texto para interpretação', 'texto-para-interpretacao', 17),
  ('Ficha de leitura', 'ficha-de-leitura', 18),
  ('Atividade diagnóstica', 'atividade-diagnostica', 19),
  ('Atividade de recuperação', 'atividade-de-recuperacao', 20),
  ('Atividade adaptada', 'atividade-adaptada', 21),
  ('Atividade lúdica', 'atividade-ludica', 22),
  ('Jogo pedagógico', 'jogo-pedagogico', 23),
  ('Quiz', 'quiz', 24),
  ('Flashcards', 'flashcards', 25),
  ('Experimento', 'experimento', 26),
  ('Aula prática', 'aula-pratica', 27),
  ('Roteiro de experimento', 'roteiro-de-experimento', 28),
  ('Vídeo', 'video', 29),
  ('Áudio', 'audio', 30),
  ('Podcast', 'podcast', 31),
  ('Imagem', 'imagem', 32),
  ('Cartaz', 'cartaz', 33),
  ('Molde', 'molde', 34),
  ('Planilha', 'planilha', 35),
  ('Documento', 'documento', 36),
  ('Link externo', 'link-externo', 37),
  ('Objeto de aprendizagem', 'objeto-de-aprendizagem', 38),
  ('Material da BNCC', 'material-da-bncc', 39),
  ('Material para SAEB', 'material-para-saeb', 40),
  ('Material para ENEM', 'material-para-enem', 41),
  ('Material para vestibular', 'material-para-vestibular', 42),
  ('Material para concurso', 'material-para-concurso', 43),
  ('Material para impressão', 'material-para-impressao', 44);

